### PR TITLE
Remove confusing sentence stating that `fatBastard()` IS a closure

### PR DESCRIPTION
**Pull request by crwhitesides**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by crwhitesides** [comment]
The sentence removed seemed to imply that `fatBastard()`, not `whatsForDinner()`, is the closure.

**Comment by aturkewi** [comment]
@jjseymour it looks like the inner function is called a closure, but not the parent function from the docs linked. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by crwhitesides** [comment]
I only mention the `fatBastard()` example in this PR, but the **Pirates and Passwords** section (using the `raspyDoorGuy()` example) has the same issue. 

This same issue trickles down into the **Closures Lab** as well. Thanks for your help!

**Comment by aturkewi** [comment]
@crwhitesides Looks like you're correct, that inner function is what would properly be called a closure. Any chance you could update this PR to catch all the instances so we don't have to merge this one in and _then_ put in another PR for `raspyDoorGuy()`?

**Comment by aturkewi** [comment]
Looks awesome! Thanks so much :)

**Pull request merged**
